---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dmutreja/oci-cli
    tag: "latest"
inputs:
  - name: stemcell
  - name: light-stemcell-builder
outputs:
  - name: image-par
run:
  path: light-stemcell-builder/ci/tasks/create-image-par.sh
params:
  oracle_region: replace-me
  oracle_namespace: replace-me
  oracle_stemcell_bucket:  replace-me