---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "latest"
inputs:
  - name: light-stemcell-builder
outputs:
  - name: oci-config
run:
  path: light-stemcell-builder/ci/tasks/prepare-oci-config.sh
params:
  oracle_tenancy: replace-me
  oracle_user:    replace-me
  oracle_fingerprint: replace-me
  oracle_apikey:  replace-me
  oracle_region: replace-me
