---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dmutreja/ubuntu-xenial-boshcliv2 
    tag: "latest"
inputs:
  - name: light-stemcell-builder
  - name: cpi-release
  - name: director-env
  - name: stemcell
  - name: cpi-release-src
outputs:
  - name: deployment
run:
  path: light-stemcell-builder/ci/tasks/setup-director.sh
params:
  BOSH_LOG_LEVEL:                 debug
  BOSH_LOG_PATH:                  ./bosh.log
